### ISSUE TITLE
Q about dependencies in dockerfile

### ISSUE THREAD

**Issue by jonathan-s** [bfirsh/django-docker-heroku-template#2]
I'm curious about what you use these two specifically 

```
  exuberant-ctags \
  netcat \
```

**Comment by bfirsh** [comment]
Netcat is to make [the test script](https://github.com/bfirsh/django-docker-heroku-template/blob/master/script/test) work.

I can't remember why ctags is in there... I think it might be related to the VSCode environment, to make some kind of autocomplete work?
